name       : khotkeys
version    : 5.15.3
release    : 30
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.3/khotkeys-5.15.3.tar.xz : 85d6705dec38e38d259bc9a721a75a9bd4abde636a1d7406bc1dc5390d6dd33e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - plasma-framework-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
