name       : khotkeys
version    : 5.15.5
release    : 33
source     :
    - https://download.kde.org/stable/plasma/5.15.5/khotkeys-5.15.5.tar.xz : 59dd6a571d52401b1963cde732b6c6c589a328438155ec0e0c5c77b5ac029127
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - plasma-framework-devel
    - plasma-workspace-devel
rundeps    :
    - libxtst-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
