name       : khotkeys
version    : 5.27.7
release    : 90
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/khotkeys-5.27.7.tar.xz : 6d85041dc59a4e0c6726c97c3f30caf6d22b8f960bcfc39fcdd294f16538efc6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
