name       : khotkeys
version    : 5.24.5
release    : 82
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.5/khotkeys-5.24.5.tar.xz : 7a2307b4ca1dca1b240a59ea4bbbceb48b1f6759c9ce3bb36b3cab7274f6a71a
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
