name       : khotkeys
version    : 5.23.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.0/khotkeys-5.23.0.tar.xz : 0f13f6842976853db42a7912da55ce25f6ad7e116740109f6255522662cb0f76
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
