name       : khotkeys
version    : 5.22.2
release    : 69
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/khotkeys-5.22.2.1.tar.xz : bfb8c9f84dd9d695edf25c3bc03c2703c4e434d3191f1883215d1dee25edb0f1
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
