name       : khotkeys
version    : 5.27.5
release    : 88
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/khotkeys-5.27.5.tar.xz : 83e85326de1e3b430ebd0364955e2167ccee50d33fdaaba9fa0e5cf488e6ec20
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
