name       : khotkeys
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/khotkeys-5.9.5.tar.xz : a995c3b0a1a86c79c64342ae17a45fd664205592d3cd541bcd7453b5d89ac617
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
    - plasma-framework-devel
    - plasma-workspace-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
