name       : khotkeys
version    : 5.18.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.3/khotkeys-5.18.3.tar.xz : e2b459da176c369fecc46a0dfa151266e4778194b3b8d81c4d7bc423301ff204
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - plasma-framework-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
