name       : khotkeys
version    : 5.13.4
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.4/khotkeys-5.13.4.tar.xz : 7d9c0d54804c8275ae69d1fee159b4c5e7a5c90aabd801df40637803965302db
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
    - plasma-framework-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
