name       : khotkeys
version    : 5.16.1
release    : 36
source     :
    - https://download.kde.org/stable/plasma/5.16.1/khotkeys-5.16.1.tar.xz : 7fae2a0b09f266cce0012037d4151dc6794e19206b729be83bba3da3f12adf2c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - plasma-framework-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
