name       : khotkeys
version    : 5.21.5
release    : 67
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/khotkeys-5.21.5.tar.xz : 2d58299f705f928f877718c1766a6dce201d728a24e88b9a24ca5e12a5f99c13
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma hotkey module
description: |
    KDE Plasma hotkey module.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
